### ISSUE TITLE
_id column does not seem to work as specified in docs

### ISSUE THREAD

**Issue by annikaC** [mitya33/cfimp#1]
First of all, thanks for this great tool!

I have created a CSV to update existing entries, and I get the error: `UnknownField: Status: 422 - Unprocessable Entity - Message: No field with id "﻿_id" found`

Sample CSV
```
_id,internalName,locale,navigationComponents
3jpUCXzwOSPynzFAQiWvUg,[Navigation Collection] [en_US] [NY],7rbkJNbNuAWIOsWKeG1Mbb,1C3p8Nykj9GH2UiuqTyPnv
```

This is what the preview shows me: 
```
{
      "_tags": [],
      "﻿id[default]": "3jpUCXzwOSPynzFAQiWvUg",
      "internalName[default]": "[Navigation Collection] [en_US] [NY]",
      "locale[default]": "7rbkJNbNuAWIOsWKeG1Mbb",
      "navigationComponents[default]": "1C3p8Nykj9GH2UiuqTyPnv"
}
   ```
Running command: `npx cfimp -space:[SPACE ID] -env:[ENV ID] -model:navigation-collection -input:input.csv -locale:default -delim:com`

Is there something I'm doing wrong here? Possibly a Contentful API update ruining our day? :)

**Comment by mitya33** [comment]
@annikaC not sure if you saw my above reply but I've finally had time to dig deeper into this. I think the confusion comes from what the preview output shows. Unhelpfully, it makes it look as though it plans to write to a literal field called `_id`, but it doesn't; when the write operation is actually run, it treats `_id` as an instruction to update an item with the supplied ID.

This can be confirmed by using the new `previewfile` arg (v. >= 1.0.32). This will quit after generating the actual JSON file that gets fed to Contentful and so can be considered a fuller form of preview.

Hope this helps!
