### ISSUE TITLE
Document example of correct csv formatting

### ISSUE THREAD

**Issue by jasloe** [mitya33/cfimp#10]
Looks like an incredibly useful tool! Unfortunately, I'm unable to get this working. The parser seems to bail out after the first letter of the first row.

Running:
```
npx cfimp -space:01vk1xo6n33v -model:property -locale:en-US -fields:"title" -input:import.csv -previewfile
```
With the following import file, where `title` is the destination field title:
```
title
first 
second
```
results in:
```
{
  "entries": [
    {
      "metadata": {
        "tags": []
      },
      "sys": {
        "contentType": {
          "sys": {
            "type": "Link",
            "linkType": "ContentType",
            "id": "property"
          }
        }
      },
      "fields": {
        "title": {
          "en-US": "t"
        }
      }
    }
  ]
}
```
Omitting the `fields` argument results in:
```
{"entries":[]}
```
Explicitly setting the title field to:
```
title[en-US]
```
yields the same result.

I have also tried this copying, pasting, and modifying your example record from the readme with the same result, i.e.:
```
title
London
Berlin
```

**Comment by mitya33** [comment]
Glad you got it sorted with the other poster's PR. I've merged that into the base and will now close this issue.

**Comment by jasloe** [comment]
Thanks very much. Will this also be published to the npm registry?

**Comment by mitya33** [comment]
Yeah I'll do a build over the weekend and send it up 👍
