### ISSUE TITLE
field names not recognised in .csv

### ISSUE THREAD

**Issue by datarishi** [mitya33/cfimp#5]
Use of -fields produced expected behaviour:

`npx cfimp -space:9xn2m7v6095a -model:project -input:test.csv -delim:com -fields:title,hideYearInfo -locale:en-US`

| test project | true |
|---|---|
| **test project** | **false** |

Without fields the command fails:

`npx cfimp -space:9xn2m7v6095a -model:project -input:test.csv -delim:com -locale:en-US`

| title | hideYearInfo |
|---|---|
| test project | true |
| test project | false |

`The following 2 errors and 0 warnings occurred:
12:20:35 - UnknownField: Status: 422 - Unprocessable Entity - Message: No field with id "﻿title" found. - Details: unknown - Request ID: b60c09f0-1236-4c5f-bae9-b5543fdb06a9
12:20:35 - UnknownField: Status: 422 - Unprocessable Entity - Message: No field with id "﻿title" found. - Details: unknown - Request ID: 63f2d119-4cb0-488c-bc5e-9daab93c08b1`

**Comment by mitya33** [comment]
Interesting - I've not had that, and most of my usage is without `-fields`. Interesting also that the error from Contentful is that there's no such field, but you're saying that, when you use `-fields` and specify the SAME field name that Contentful otherwise didn't exist, it works OK?

**Comment by mitya33** [comment]
Closing following no further reply from OP. Feel free to re-open if still an issue and can provide more info.
