### ISSUE TITLE
can't update fields displayed on Contentful as 'Dropdown'

### ISSUE THREAD

**Issue by datarishi** [mitya33/cfimp#6]
Can only upload text data for fields when their type is set to 'Single line' rather than 'Dropdown', even when the submitted text exactly matches validation criteria.

The workaround is just to change how the field is displayed on Contentful to 'Single line'. Not a massive issue, but not always ideal.

**Comment by mitya33** [comment]
That's odd. I see no reason why Contentful's display rule for a field would have any bearing on its performance in a data model sense. Surely whatever the display rule, it's the same type of database column in their back-end. Do you get an error?

**Comment by mitya33** [comment]
Closing this as insufficient info to reproduce and no further reply from OP.
